### ISSUE TITLE
Build new docker images

### ISSUE THREAD

**Issue by marcj** [php-pm/php-pm-docker#10]

**Comment by acasademont** [comment]
Hi @marcj just a question, would you please care to explain the `trapIt` function for starting ppm? I'm no expert on Docker containers and would be nice to know how does that help. Thanks :D

**Comment by marcj** [comment]
I had this already covered, try to search the issue tracker 👍

**Comment by acasademont** [comment]
@marcj i'm sorry but i couldn't find anything, that's the first thing i did before asking

https://github.com/php-pm/php-pm-docker/issues?utf8=%E2%9C%93&q=

**Comment by iBobik** [comment]
I am also interested. I guess it is related to that harakiri with workers spanning, but I do not understand why you do it in a Docker container. Best practice is to have one worker in a conteiner and then scale service (in Docker Compose or some orchestration).

**Comment by marcj** [comment]
Oh, sorry guys, it was on Twitter :) https://twitter.com/docteur_klein/status/950370544574255104

**Comment by ties-v** [comment]
Nice project guys!
Any chance the docker images on dockerhub will be updated anytime soon?

Maybe it is possible to build a pipeline that updates the images for each new php-pm or php-pm-httpkernel version in the future?

**Comment by iBobik** [comment]
Just a suggerstion to make updates more easier to maintain:
I use GitLab CI to build all tags of base image, so I do not have to care about new PHP versions.

About it: https://github.com/iBobik/drupal-composer-docker#tags
Script: https://github.com/iBobik/drupal-composer-docker/blob/master/.gitlab-ci.yml

**Comment by marcj** [comment]
phppm/standalone:1.0.3, phppm/nginx:1.0.3, phppm/ppm:1.0.3 build & pushed
