### ISSUE TITLE
2.0 release builds?

### ISSUE THREAD

**Issue by 1allen** [php-pm/php-pm-docker#21]
along with some newer php versions builds?

**Comment by 1allen** [comment]
fyi https://hub.docker.com/r/experium/php-pm-nginx

**Comment by andig** [comment]
ping @marcj the docker images at https://hub.docker.com/r/phppm/nginx/tags are over a year old. Would you mind updating or adding me to the docker hub org? Refs https://github.com/php-pm/php-pm/issues/490.

**Comment by marcj** [comment]
@andig invited :)

**Comment by andig** [comment]
doh: work on me ;)

**Comment by andig** [comment]
Released 2.0.3 builds

**Comment by andig** [comment]
@marcj could you also add this docker repo to the gh devs team? Can't close issues here, not sure why...

**Comment by marcj** [comment]
@andig done 🙏
