### ISSUE TITLE
update alpine

### ISSUE THREAD

**Issue by wanghanlin** [php-pm/php-pm-docker#7]
Can we update safely to alpine 3.7 instead of current 3.6?
alpine 3.7 ship nodejs v8 in apk, but its v6 in 3.6, it can easy some work.
if it's ok, i can submit a PR

**Comment by marcj** [comment]
We don't need nodejs in our image, so why would we need to update it?

**Comment by wanghanlin** [comment]
Hi @marcj you are right, although to be honest i can benefit from it when building image based on php-pm,  I also think always use the latest base image is not a bad idea.
It's just a suggestion from me, if you think we should wait php 7.2 be in alpine pkg and then give it an update, I totally understand that.

**Comment by wanghanlin** [comment]
@marcj  Thanks!
